
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:13
    command: -p 5432
    environment:
      PGUSER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DATABASE: ${DB_NAME:-vestir}
      PGDATA: /data/postgresql
    volumes:
      - postgres:/data/postgresql
    ports:
      - "5433:5432"
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@vestir.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
      PGADMIN_LISTEN_PORT: 1111
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "1111:1111"
    restart: "unless-stopped"

  vestirbackend:
    build:
      context: ./
      dockerfile: vestirbackend.Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    container_name: vestirbackend
    volumes:
      - app:/usr/src/app

  volumes:
    postgres:
    pgadmin: